# Generated by Django 3.1.1 on 2020-10-02 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Mss', 'Mss'), ('Dr', 'Dr'), ('Sir', 'Sir'), ('Madam', 'Madam')], default='Mr', max_length=15, null=True, verbose_name='Title')),
                ('fulltname', models.CharField(max_length=125, verbose_name='Full Name')),
                ('othername', models.CharField(blank=True, max_length=125, null=True, verbose_name='Othername (optional)')),
                ('gender', models.CharField(choices=[('Individual', 'Individual'), ('Business', 'Business'), ('Institution', 'Institution')], default='Individual', max_length=255, verbose_name='Gender')),
                ('quarter', models.CharField(max_length=125, verbose_name='Current Quarter')),
                ('address', models.TextField(blank=True, help_text='Address of Business Place', max_length=125, null=True, verbose_name='Address')),
                ('tel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone Number 1 ')),
                ('tel2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone Number 2 ')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Non_Active', 'Non_Active')], default='Active', max_length=15, null=True, verbose_name='Customer Status')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterModelOptions(
            name='catergory',
            options={'ordering': ['name', 'created'], 'verbose_name': 'Catergory', 'verbose_name_plural': 'Categories'},
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Full Name')),
                ('cost_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bakery.catergory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created'],
            },
        ),
    ]
